query Menus(
  $name:String!
)
{
menus(
  name: $name
  )
  {
    items {
      navitem {
        post_name
        post_title
        id
      }
      children {
        navitem {
          post_name
          post_title
          id
        }
      }
    } 
  }
}